name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
        working-directory: fashion-try-on
      - name: Lint
        run: npm run lint
        working-directory: fashion-try-on
      - name: Test
        run: npm test
        working-directory: fashion-try-on
      - name: Build Android
        run: npx eas build --platform android --profile android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        working-directory: fashion-try-on
      - name: Build iOS
        run: npx eas build --platform ios --profile ios --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        working-directory: fashion-try-on
